apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: db1
  description: Stores 
spec:
  type: database
  owner: guests
  host: "192.168.0.153:3306"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: db2
  description: Stores 
spec:
  type: database
  owner: guests
  host: "192.168.0.112:3306"
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: env-dev
spec:
  type: environment
  owner: guests
  lifecycle: experimental
  dependsOn:
    - resource:default/db1
    - resource:default/db2
  

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
  annotations:
    backstage.io/kubernetes-id: value
    dev.azure.com/project: observ
    dev.azure.com/build-definition: "(Deploy) [Deployment] staging"
spec:
  type: website
  lifecycle: experimental
  owner: guests
